topic:
  name: reservation

server:
  port: 8080

spring:
  application:
    name: rentalreservationservices

  datasource:
    url: jdbc:mysql://localhost:3306/rentalservices
    username: springstudent
    password: springstudent

#  datasource:
#    url: jdbc:mysql://localhost:3307/rentalservices
#    username: springstudent
#    password: springstudent

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: "10.40.94.213:9092"
    producer:
      keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
      valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: "http://10.40.94.213:8081"

logging:
  level:
    org:
      springframework:
        security: DEBUG


